apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lpEV0x4fpbIw2JeImyEox4i1mLoicRBJKUAybB1x1RjXobAN,iv:ckeUAid9PJlMT2pKGHfQQdVnzHiYntRKoIN2IpNaykw=,tag:99UDHka4q0s4OJBpEaYcPA==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:anRuQp5yUL0wY7cnFdT/hxBvwQ4edCHexi8AILnr2RJvuT44vPi4QyfuPm4=,iv:DmgK2rmdEUgzfB1AVlEe8nqyB68iS8KYb9D4dzDpaIQ=,tag:+E/kEFHULpPafTo3ZxQ6FA==,type:str]
    credentials.json: ENC[AES256_GCM,data:XurBYBQTylWYcSzXqly3+iZHGsSrLzmjqVHATjeKzVSqI4baSQtQ5vTroY8QKoiV/bYj0fbAIl/ttaQ8ftjhX5FTqc8y7Inkkfo6JOwkKa1S8Lr8zH6ezGhDdFUw2FmfMccoM5wnQej/70XlIIsXiJEsp0coZSb7aD2d2whAWXnWoH0=,iv:qVpMb+rsTIdpNuYubQ6zw4KDSBZdg+dscr9cFhagP8k=,tag:Jaab2EqQX4T2eYl0mFRS3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b29PLzlpcy82c3VYdmNC
            c0RyMDdvVkU2OEVrenlxNzMwMFpTYzZRZEhnCjJ4NVhtZVluazM0cjYvaEc4czR0
            bVFiQU1rZmV5T0NWNzJWNEErc1ZqQ0UKLS0tIFFhWHNjR2pWRm1kNGdzTHRxa0tJ
            cDdyeDJJZnlNTjk3UDcrQ25FRTd0MmMK9LJqPgxsGoLxzea1TNq4URdqVq2FYMjy
            SvoDqtT07HBaV/h11hj53iUiWXFzcbbDTunJG8B007wsHSmkAiZOmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T12:21:25Z"
    mac: ENC[AES256_GCM,data:FJhPduuxqJvA02MNY+KVUmz63TNUsHbCAq9G4nykEIA6Ru3hZdaX16ivB70FoQLqwzUuyedKZ0RA8od0j0ifWe7hZR2aM/SJHYF0CaTQSpR3kI0t5/CGfx6P0QCJ9FKOeJnAR4sPyThgGWGy1VG67PUDAJ6BNqEqsDziLEzN9b8=,iv:XpY92v/50J/LjBgu6rZpUZG686Ns7ss4EHf3De3zDRg=,tag:H7+5tiT+MHcBlvituTjO3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
