apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FcjbCN2GdDaRERpG1Sf5zpT8cxjUM3EE7rAqvC1U9lV8JvVB,iv:iEp5a9SA0ddnMyAb4WDT5M+tVVS6+x82Oz81UMnk6v4=,tag:bnLABkounvmYtrRRehiJ4g==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:KTCUZH4BypeYbr71NT9DByiB2NNJA0XAsWWIRK+qqah8L+O2JaqisxNXUwOdmVP4AtMtf/yA2o+YGc1rYqHRoyuwPPwgy2hEnp4jBU4kLMf/IBwrmnLDu6qQ88nA/Xln7dAKZDUiplvxZsVY58N1RFQYoGLjhtEkz/jBR9QjG8nFeeLO++HZA3o9OKBExImii9eEaGEfbIpgdk2uTb+YZgQbRHudhoTM8jkX7zMAqA==,iv:cuagXsJjOrJTbkna5zbuo+V62Wh/HlxDZxThGDhbfZs=,tag:NKIH0VsfDNMJAxYbs4MFoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMDBKNitUbjNzN0V4K0NC
            eS9SbXZwUlhYazNlcytZZTZCMDFGejFwY0F3Cm95RzJpdTFJbWVvdlhXMEJTcG9Z
            dUl4d2pVdGt0Q1gyY3MvOEpqS2k0eEkKLS0tIEl1UWNKeUZWREdHd1JjUDJYdU9B
            MkRlV1JFRDZDMFJza2k2a0x0aW01NTAKaYsoTuvgLRlEMgZpB4GgJKBS5OmJlIKj
            teVKg2Rp060ReMn8qRgRq6cq/vTXzgRHMd0qZekC26GjrShVEpWzvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T13:13:30Z"
    mac: ENC[AES256_GCM,data:GZzFFIWIy3y2z+kD1JReaWnh6wj5r4AfeZDC8rgOj2QnoJ+zinkS7ZRYzVy3KS32m8GcxzljAH6ud6+qixAzbdI3g1tCVTDhI7G+B19uMpFSOc2rrIWpA3dqxfGnJ+uW2NpuX16RPe0oeMGMdUt8lyNNtPXeyuYB66jlaL18zhQ=,iv:H5Qa0jvu40peymfd/hgrO1zz15XJi9ymEAftAW59E3k=,tag:5NPvmcK6MSdNlp/mddgb+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
