apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:KdTH72SHwp/nxWHp2EAYKgGYR4iDpBqJbTluhzBLk5sKdg6utyphTQ==,iv:NgxhqasupaJwsF9UcC1ptTNLMSzGJZQXOChR5DCgUcs=,tag:GxB/A5vYUqd1oxDgfsW4pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOHkyOVprc3RsVisxYmtN
            NTltWmdobmRVZ0JwS214VjAxTGtubitGOWdnCno3NEcwNFljb1laUk5KdUtRakIx
            UEc2YjFGTTVDa2JmUFJoTlFiM2l3N2cKLS0tIFBnV29KTFFsRjhhVER1MFRZdWV1
            L0lDQnp3dE9haGRVOGtvaUxvRDlseEEKxNkjAM2WIJ6cy6D10RxObU7zK3o91UZZ
            byDS9DejYBcqptA/2bHUVCCPux0hHsrjD+1C8wi8/BnDhPpAeXmLtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T12:21:25Z"
    mac: ENC[AES256_GCM,data:5xYGUKN1K1iaD3zjxMsxmOwm/2SZu4fW0OIayqb4kJnfgWskjqBcAkQUAa6ZwT/uFRlSkkntn44zt5k0HWn9qkZzWZMrmFY2A1jOKOZWXuynmn+GrN2wdsvJQ9F/DLP9qCis8CsauCVGbq5nKikIiYEjCU5mzjjNMKv4dDag7Xg=,iv:9QixaKFOfPVWZIb4Iu/Q69yKG9XrYAPF5uCFOR8SvAk=,tag:dSDRIkUV/RhK6APf473wxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
