apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:4oNDgggKptiKiaISGIOgqAOtgByZPo5cd5Vse5aAwk9rX8E2YPyUJA==,iv:V0wxq5hcIvila0l7u/CQwyxls06uCXczusABfgh8aV0=,tag:pIzFiyfMgKmG0qJbtr3IZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTjBSeWluRFlLMHg5eDho
            UzJvWjcyZnlaeTlwbG1velJCMnhBRWEwalI0ClVTWGhhWVJCckN0eUpONDF1NUdB
            clU5WklNZFNpdjFqTWh3aGVEZXczWTAKLS0tIHdFd3M5WVRzSFFzS0tDNTdMcUhU
            TzZaNFVHaDZ2Z1I2NnVsYm9oZFRzMWMKxdgZfT1Cw1DCcXvETCAayF47d4p485P2
            wmdzziiDEbi7k34OIWFGCAEmjr1LjK+nsbTb2sQ1L/Y7rbrqWHeXWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T13:13:30Z"
    mac: ENC[AES256_GCM,data:hBj9ksIRi+Y68eqQ0Ls+aqVEsHq/QsEeOswcM85J4ro9/Mh0y9mRNCsU2H0YUbEJobNJrrIiZ/xCcoYWIZVTLsuFvguo4RiOyYm60b0ySOb8hqmjY9Q5anVwypzWPNUEPpV/l4NllJw7SWNr6sJ4NL4ypfCsMtwsjvHnDDaVCbM=,iv:Ucqh2oGYqbU60HODn7l8F93WLm0bnGPDd2+NhLKsHk8=,tag:zIKroOIukS0aVlE59MJBNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
