apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:3ydAhtOrfYtJon0dAWNKKG/S0roUr5S5ytiY+pZ9fUjPuPKeG/P7kWpHrV+U6OqMmgSFxSZVeUrpihbm7ReD+QflPy3Tdj+YEY2aOQG0ylGg5677g+q70cYXipmm1Q==,iv:gEd0gP7suilBirNIcZ/TGDbV0HLGSca4KWlFZiCidg4=,tag:sgu/7AXRNOjuoJ4Yc7Q1oQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:AWShm6x2RxYPD/WZ9oRy,iv:BoQJBuLLZrgNtbRPPSorZi4aAFljUK8k6P38ULIgric=,tag:A4WD5pyMcRgNOxxurh6QPA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:24Ri/QKwWOOzi01lVyU+MLq9/Vrl,iv:oa9sQ25VHwSTiwXwTCTT9V0wlxQG+ApYWSoxjirYqoM=,tag:H+dBaFC0D0IWUwDKuuOG0A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lpDVBj0kMOWQ2vPnwRnCaSAMPH4fobJwySc/WhJJVVo71EIm,iv:1mhkKGHmc3NjuukogTLTCjjMMgtqw+tFHDuxfDVP3zw=,tag:diEn2OZYanzBYrdCUB6oPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVzVLVlBpeVl0eDdtVkJU
            UVoxQzBZRWRWYVRhT2lBcFFXRi9yYWNQS1RjCjBvK0xsRGU2eWZzdVZuN1JBYVZB
            Vm9ORzc4Q0FIZ3M4MVM2ekxtbE4zZFUKLS0tIExSUVl5eUxpRmlrNlpVa0ZWWHNM
            YWZ5VUlVek5DTkRMZC9KRXhZd09Lc2cK9G1e5pRfWKQNO30d/HbXiMFbKRyQgtTS
            By072fUvAAeZI4Leu+y6Kd9qhVkIyEIf+5rZQs7mInwiQC+0x8EmqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T12:46:42Z"
    mac: ENC[AES256_GCM,data:5xG/3DMjujbXcXrm+TsFNIu0AqDc4qDS1KEpurfZoxnYCOUXNCspR74UfVvifj5hSAnqrfutweWmhq50hOzoVGRoOzxdh2TaT0aM4pNWPi8nELf91E5/0etm2MzpSM4aZ7CzVBN0FoNY1VhFlAM9A7hOe87oMKrD4L9OVwh5EMY=,iv:dF30EagkvSp2PUMe5PN97ArAoAg0iQ4pAS1dsEFL1Dg=,tag:xgAYVhqlmSDA+q57C5Vy/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
