apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:f3YT59+czyP4LIsWgdkj5BvzLMa+mPmMSt2I4ab0qr0/52E2RGXSaP6i4oVRtMJwtSbc1fgQC3gYyedkdaL4HlYFJe9sf+7fF0KSxrQm8M1fg2LI8EO+Gxar/Qp8+A==,iv:43E1iEgi+hiQ9K2WONxDda2iyL8sPNKYvpSa+1DRhWk=,tag:MZbOpMFK/+3k4xxMeswgQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMzZTMmlLZkZkbTVoNXg2
            TlhJdWdQbHhXdEV0T1FzSDMyeUhPVnBHR3dRCjhqZkk3dEoyVWhJU2hkTXVuc29q
            WS9ZK1JNNnJENkxHVEVBbzlleFZnYVEKLS0tIG1ZT0U1QytZN2d4RGlBeURyZS9N
            NWtnUlJHN3Uzci8vREZEUXBOUUFHUHcKypCghxQpM2CzWgABEw8FDntDLHyTqHH4
            ISgqGVsMTdJ3vYMKw102nHP+p1VKKsxESQ7WrL7A9V5zqW0oQkGgNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T11:25:54Z"
    mac: ENC[AES256_GCM,data:yXy9LN2nZ1xGYw2Jv0U81dms6ze0aqB9nUmiBtRzoQAne1D+AKZvQDYCSf4rVDTEoyRBw/bEEyM2qCEUNTUiYH/frdcj4HPe52/ikj5+qcuBBTHo18LsPg47+HsRwzUBg6SWLonxLGCxirLZHL3GOJXBXwHghNeJebdwfMLIKYI=,iv:lfBdJY18VioA5YAWOiV5UYMbRTZPmV9FXgEAtAnlkBU=,tag:rSgRyeeLLUZZZh2O7cYVxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
