apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:6RIPWZ6cMLnqM3pE5ib4XNY0riCMTMMujMUF+IRuo/4=,iv:f0sgNxt8N6LLeo9vyIF2rxxkjqPd+vU/krJE3uX6iR4=,tag:IEiUdZ+qfDrQSX9dzJBB+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWejg3Ky9QbTM0bUFKRGt0
            L0NGYnRLNEhKbUhUWVJ1aUpHMnZXRDZURVdRCk54SW9JVHJWem9SOTV1aXE4Q0F2
            RzlCcnpnblF4ZEZ1V2lRamlveTJNQ0kKLS0tIFlFMFV1Q2xneU80bHZLVUsrWHZz
            ek9HQXg4VW9lU0huMUU4WEdGMmlCV1kK/UILXFa5+GpB5e+9BEWbPeucUC8AJMxT
            sI99VAD9AF+ggMspqs7w3kZBiU8Z4sOisR/vI0O8z3NFZTVcQzzulQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T13:13:30Z"
    mac: ENC[AES256_GCM,data:EF8k7mzE5V+e1EWwZiNuaoRGACJbpHTJI9OixxYi5QncE2rWxvfuzoBDjjoCLY/uSi11qhS2EfNdKIVgKslQaQqPzBGdW2o0TIf/1p7i8/tfbOwn642vRu4PJCkj2X9HmjgX0eoHsInq5/sPZvaj51vbakle/d5uRFFWc6DOJFc=,iv:ylvvgs7G3+JF6rtTgMoH7T3jy9yDZqF2cTcqlZBIu3o=,tag:R+FLHNJ5SXTpfIQLLSGNSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
