apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:dJhUlHm0WeKoqWecmVHGR7G9xyPMtKgPAb9wstKoz1U=,iv:rT+evgCpCID9pvbIYil/SBsUJrV1K7vGPUQFXNXOr2A=,tag:3dX7f+UiD1eGRzh0AlyHkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbitEc3BkcnRpZkZVNXJR
            VVV2ZllqbnpqYmRUWk1wL0QrcTk0SGcrL2tFCnpjb2RORzhPMWJxRFdBUVRVOWlH
            RW9kNVlXYlpJUEVxczlTOGNlWmkzeFUKLS0tIFNITk5iRStSWG8rb0p2clNLNG9Y
            dmxSV0ZnM1ZNNlZScjlSOHpZQjNNMUEKJvAlo43BX6o3OpQhP6FP5H848J85kQT4
            ZZQ9bNSJw2HyKTZrlVWLzElLK0XFh2ddnzECLHMU8VPVyB9jW1y+DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T09:13:17Z"
    mac: ENC[AES256_GCM,data:e1fkHq9ZmsTtB/nYfq9TZMlmB11qXdJy/Zpa+Ve2ISP+EJqhPWcbg5o3iAdYIMlhd9lC4C94kOTU5SkKZz+2nKu8jjA2agHapFoaDNEi3FbttPxVWaUaLMggXmlSNJ70CP5BTTLU7PxF0bd2Jf/JRYUMZNKSGHYwqrPWfcbe4ms=,iv:MBJfxYWt8cN75ipzFbETpT70qURy+wph4h7TuOC76z4=,tag:5rAd24velSoZL7fnih3H8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
